# Generated by Django 3.1.1 on 2021-03-01 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Socialmedia', 'Socialmedia'), ('HealthManagement', 'Heatlhmanagement'), ('Entertainment', 'Entertainment'), ('Educational', ' Educational'), ('Productivity', 'Productivity'), ('Lifestyle', 'Lifestyle')], default='Socialmedia', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_facing.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
